name: Greeting
on: [push, workflow_dispatch]
jobs:
    greet:
        runs-on: ubunto-latest
        steps: 
            - name: Get Code
            #   run: |
            #     echo "cloning repo.."
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/${{github.repository}}.git
              uses: actions/checkout@v20
            - name: Install Node 21
              uses: actions/setup-node@v4
              with: 
                node-version: 20
            - name: print node version
              run: node -v
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm run test