name: Greeting
on: [push, workflow_dispatch]
jobs:
    greet:
        runs-on: ubunto-latest
        steps: 
            - name: Get Code
              run: |
                echo "cloning repo.."
                echo "${{toJson(github)}}"
                git clone https://github.com/${{github.repository}}.git